language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE rtd_db_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: bqcHkWHFppm471btGWBj+5wyxvg8OIaVIcQVeb3uZgYrw6AgMgiO3CG9xpHAkF88BguEFi9mgFIymQEjf2XhlccdaHZsc+ttPlvJVNI0xZeUNTPpQPD31Nk6yXEw5AcNnJPJWhp22NECRKukg6c3y1stvFq3MLVV2itbgEl98FDirbCmHb43z9Qe0j+Pk/u0EhEMxdxgpifwaD7j6wfGrWP3oHOgxkUYd3iAI5z+hvjvZLCFY+6lxBFSCHO4RcdS9RQR1YNxRIF0BTyGLPJuM7xtr5Cz6TPtmt5FeHayWCCsAnTA4u3xhmyXNU4jo85T6J71PIvB05LMhzgdifbB2/eKatSc3KEMxLPggdm1Udz99a7ikCsqqkxigbyBPkteevlQYm6J94594KRmXaHoSHaSWIBClH6dRgHhwvwYHl1dt8WW8inXLFWFDb82mXjOwXvTAweVFfZETaBGmXbxW+aX3HEHTof+Rin6wkcwjdtfTN4XfwyWZOEu+TN+YdWK9ExEO8P8XZqnulxLW6xMwmEjFLkQDWh5YDdKAdfIXZRL/V0gEipbajv2ciAtLxDSk4ncwvrhXCOYIoChLRawA6qBrIKRSzD0s/xBQw3r8gBuBCZYK8oa4yaGAPW/Vewoq53zTe+aBkIuh97yG9gpKGpVkUm885Zpfpu/VYcJKo4=
  app: byob-2018
  on:
    repo: andrew-t-james/byob
